#!/usr/bin/env bash

SCRIPTS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source ${SCRIPTS_DIR}/setup


function debug {
    SECURE_SCHEME="http" python run.py
}

eval_in_virtual_environment debug
