#!/usr/bin/env bash

SCRIPTS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source ${SCRIPTS_DIR}/cloud_foundry
APPLICATION_NAME=$1


cloud_foundry "push" ${APPLICATION_NAME} "-b python_buildpack"
cloud_foundry restage ${APPLICATION_NAME}